task: "search_point2_red_eval"
model: "gpt-4o"
max_workers: 16
request_interval: 5.0 # 请求间隔（秒）
output_base: "./search_psy/results_v3_based"
data_dir: "./data/results_overall_deepseek_v3"
N: 10
api_params:
  max_tokens: 8000
  temperature: 0.7
  top_p: 0.9
data_processing:
  "content_field_a": "analyze_0.chunks_results.0.content"  
  "content_field_b": "analyze_0.chunks_results.0.content"  
  extract_fields:
analysis:
  min_consensus: 2
  output_dir: "analysis_results/"  # 自定义输出目录
system_prompt: "你是一个军事策略分析专家，下面是陆战兵棋夺控战（以争夺关键地域或目标为核心任务的战术推演想定）中的两个玩家的战术复盘，包括玩家方单位的所有行动。"
user_prompt_template: |
  对局A:
  {contentA}

  对局B:
  {contentB}

  首先，分别分析复盘关键帧中玩家对哪些单位采取了哪些行动；然后，根据"推演后期夺控点争夺情况"，分析哪一位玩家行动的风险更高。
  请给出分析过程，在回答最后用++A++或++B++说明对局A片段还是对局B片段的玩家行动的风险更高。
