task: "search_Risk_red"
model: "gpt-4o"
max_workers: 16
request_interval: 5.0 # 请求间隔（秒）
output_base: "./search_psy/results_v3_based"
data_dir: "./data/results_overall_deepseek_v3"
N: 10
api_params:
  max_tokens: 8000
  temperature: 0.7
  top_p: 0.9
data_processing:
  "content_field_a": "analyze_0.chunks_results.0.content"  
  "content_field_b": "analyze_0.chunks_results.0.content"  
  extract_fields:
    - name: "action_A"             # 新增字段
      pattern: "<action_A>\\[?(.*?)\\]?</action_A>"
      required: true         # 不允许匹配失败
    - name: "action_B"             # 新增字段
      pattern: "<action_B>\\[?(.*?)\\]?</action_B>"
      required: true         # 不允许匹配失败
analysis:
  min_consensus: 3
  output_dir: "analysis_results/"  # 自定义输出目录
system_prompt: "你是一个军事策略分析专家，下面是陆战兵棋夺控战（以争夺关键地域或目标为核心任务的战术推演想定）中的两个玩家的战术复盘，包括玩家方单位的所有行动。"
user_prompt_template: |
  对局A:
  {contentA}

  对局B:
  {contentB}

  首先，分别分析复盘中玩家对哪些单位采取了哪些行动。
  其次，请在这两局复盘中各寻找一个片段（明确时间步），要求这两个片段中玩家操作的单位相同，但策略不相同，且最能反应出两者风险偏好不一致的片段。
  请给出分析过程，分析完成后，以"<action_A>时间步，对局A片段描述</action_A>; <action_B>[此处填充对局B片段描述]</action_B>" 的格式描述片段中的玩家行动，在回答最后用++A++或++B++说明对局A片段还是对局B片段的风险偏好更高。
