task: "search_Risk_seeking_blue"
model: "gpt-4o"
max_workers: 16
request_interval: 1.0 # 请求间隔（秒）
output_base: "./search_psy/results_v3_based"
data_dir: "./data/results_overall_deepseek_v3"
api_params:
  max_tokens: 8000
  temperature: 0.7
  top_p: 0.9
data_processing:
  content_field: "analyze_1.overall_result.0.content"  # 点分路径语法  analyze_1.overall_result.0.content
  extract_fields:
    - name: "action"             # 新增字段
      pattern: "<action>(.*?)</action>"
      required: true         # 不允许匹配失败
analysis:
  min_consensus: 4
  output_dir: "analysis_results/"  # 自定义输出目录
system_prompt: "你是一个军事策略分析专家，下面是陆战兵棋夺控战（以争夺关键地域或目标为核心任务的战术推演想定）中的一场战术策略总结。"
user_prompt_template: |
  {content}

  在心理学，冒险倾向是指：
  在决策中为追求高收益/目标，主动接受不确定性或风险的倾向。
  高：决策优先考虑目标达成速度，主动拥抱不确定性，风险识别阈值高，受挫后易强化冒险行为。
  低：严格遵循风险控制流程，行动前要求充分的安全冗余，倾向放弃高风险高收益机会以维持稳定态势。
  请回答：
  找出对局中最能够反应出冒险倾向的一个典型行为（明确时间步），并说明此行为是高冒险倾向(A)还是低冒险倾向(B)?
  请一步一步思考，并给出你的思考过程，思考完成后，以"<action>典型行为描述</action>的格式"描述典型行为，在回答最后用++A++或++B++给出选择。
